// https://github.com/open-sauced/open-sauced/blob/main/.github/workflows/assign-yourself.yml

name: Assign
on:
  issue_comment:
    types: [created, edited] // action runs on new and edited issue comments

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      # .take in an issue comment.
      - name: take an issue
        uses: bdougie/take-action@main
        env:
          GITHUB_TOKEN: ${{ github.token }}